-- To find the second largest number...
select name,salary from manager order by salary desc limit 1,1;

--To find the 3rd largest number...
select name,salary from manager order by salary desc limit 2,1;
